# Generated by Django 5.2.1 on 2025-06-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_sportivo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personale',
            name='ambito_competenza',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='personale',
            name='orario_servizio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='stato',
            field=models.CharField(choices=[('attesa', 'Attesa'), ('annullata', 'Annullata')], default='attesa', max_length=15),
        ),
    ]
