# Generated by Django 5.2.1 on 2025-06-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_sportivo_app', '0002_alter_personale_ambito_competenza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenotazione',
            name='stato',
            field=models.CharField(choices=[('attesa', 'Attesa'), ('annullata', 'Annullata')], default='Attesa', max_length=15),
        ),
    ]
