# Generated by Django 5.2.1 on 2025-06-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centro_sportivo_app', '0003_alter_prenotazione_stato'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('calcio', 'Calcio'), ('tennis', 'Tennis'), ('padel', 'Padel'), ('basket', 'Basket'), ('pallavolo', 'Pallavolo')], default='NULL', max_length=20),
        ),
    ]
